name: Parallel Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  BuildTest:
    name: Test in ${{ matrix.service }} container
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - service: gui
            image: ghcr.io/${{ github.repository_owner }}/tricys_om_gui/base_om:c72d8c4019223790c68065b1330de2338c9a8df2
          - service: ompython
            image: ghcr.io/${{ github.repository_owner }}/tricys_om_ompython/base_om:c72d8c4019223790c68065b1330de2338c9a8df2

    container:
      image: ${{ matrix.image }}

    steps:
      - name: Run Build and Test Steps
        uses: ./.github/actions/build_test
      
      # This step runs only if a previous step has failed
      - name: Debug with tmate on failure
        if: failure()
        uses: mxschmitt/action-tmate@v3

