name: Build and Push Docker Image

permissions:
  contents: read      
  packages: write 

# This workflow runs on pushes to the main branch, or can be triggered manually.
on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    #paths:
    #  - 'docker/*'
    #  - '.github/workflows/build_publish.yml'
  #push:
  #  paths:
  #    - 'docker/*'
  #    - '.github/workflows/build_publish.yml'

# Environment variables available to all jobs in this workflow.
env:
  # The name of the Docker image you are building.
  IMAGE_NAME: ${{ github.repository_owner }}/tricys
  # The path to the Dockerfile.
  DOCKERFILE_PATH: ./docker/tricys_om_gui.dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Use a strategy matrix to run a job for each Docker stage.
    strategy:
      matrix:
        stage: [base_om, tricys] # Define the stages you want to build and push.

    # Sets the permissions for the GITHUB_TOKEN for this job.
    permissions:
      contents: read   # Needed to check out the repository.
      packages: write  # Needed to push Docker images to GHCR.

    steps:
      # 1. Check out the repository code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx.
      # This step is required to enable the GHA cache backend.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to the GitHub Container Registry (GHCR).
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Extract metadata (like tags and labels) for the Docker image.
      # The image name is now dynamic and includes the stage name.
      - name: Extract Docker metadata for ${{ matrix.stage }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME_BASE }}/${{ matrix.stage }}
          flavor: |
            latest=true

      # 5. Build the Docker image for a specific stage and push it to GHCR.
      - name: Build and push ${{ matrix.stage }} stage
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          # The 'target' parameter tells Docker which stage to build.
          target: ${{ matrix.stage }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
