name: Parallel Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  BuildTest:
    name: Test in ${{ matrix.service }} container
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - service: gui
            image: ghcr.io/${{ github.repository_owner }}/tricys_om_gui/tricys:4f6c5feb5e30aa4e2f7399cf97f9c24f7b19f038
          - service: ompython
            image: ghcr.io/${{ github.repository_owner }}/tricys_om_ompython/tricys:4f6c5feb5e30aa4e2f7399cf97f9c24f7b19f038

    container:
      image: ${{ matrix.image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Build and Test Steps
        uses: ./.github/actions/build_test
      
      # This step runs only if a previous step has failed
      - name: Debug with tmate on failure
        if: failure()
        uses: mxschmitt/action-tmate@v3

